import { ImageURISource } from "react-native";

export const icons: { [key: string]: ImageURISource } = {
  "academic-cap": require("../../../assets/icons/academic-cap-svgrepo-com.png"),
  aerial: require("../../../assets/icons/aerial-svgrepo-com.png"),
  airplane: require("../../../assets/icons/airplane-svgrepo-com.png"),
  "at-symbol": require("../../../assets/icons/at-symbol-svgrepo-com.png"),
  bitcoin: require("../../../assets/icons/bitcoin-svgrepo-com.png"),
  "book-open": require("../../../assets/icons/book-open-svgrepo-com.png"),
  bookmark: require("../../../assets/icons/bookmark-svgrepo-com.png"),
  box: require("../../../assets/icons/box-svgrepo-com.png"),
  "briefcase-alt": require("../../../assets/icons/briefcase-alt-svgrepo-com.png"),
  building: require("../../../assets/icons/building-svgrepo-com.png"),
  "bulb-on": require("../../../assets/icons/bulb-on-svgrepo-com.png"),
  cake: require("../../../assets/icons/cake-svgrepo-com.png"),
  cash: require("../../../assets/icons/cash-svgrepo-com.png"),
  "code-alt": require("../../../assets/icons/code-alt-svgrepo-com.png"),
  "credit-card": require("../../../assets/icons/credit-card-svgrepo-com.png"),
  desktop: require("../../../assets/icons/desktop-svgrepo-com.png"),
  diamond: require("../../../assets/icons/diamond-svgrepo-com.png"),
  dollar: require("../../../assets/icons/dollar-svgrepo-com.png"),
  edit: require("../../../assets/icons/edit-svgrepo-com.png"),
  "Frame-1": require("../../../assets/icons/Frame-1.png"),
  "Frame-2": require("../../../assets/icons/Frame-2.png"),
  Frame: require("../../../assets/icons/Frame.png"),
  ghost: require("../../../assets/icons/ghost-svgrepo-com.png"),
  gift: require("../../../assets/icons/gift-svgrepo-com.png"),
  globe: require("../../../assets/icons/globe-svgrepo-com.png"),
  goblet: require("../../../assets/icons/goblet-svgrepo-com.png"),
  heart: require("../../../assets/icons/heart-svgrepo-com.png"),
  "home-alt": require("../../../assets/icons/home-alt-svgrepo-com.png"),
  keyboard: require("../../../assets/icons/keyboard-svgrepo-com.png"),
  lamp: require("../../../assets/icons/lamp-svgrepo-com.png"),
  mobile: require("../../../assets/icons/mobile-svgrepo-com.png"),
  "more-horizontal": require("../../../assets/icons/more-horizontal-svgrepo-com.png"),
  mug: require("../../../assets/icons/mug-svgrepo-com.png"),
  phone: require("../../../assets/icons/phone-svgrepo-com.png"),
  scissors: require("../../../assets/icons/scissors-svgrepo-com.png"),
  "shopping-bag": require("../../../assets/icons/shopping-bag-svgrepo-com.png"),
  "shopping-cart": require("../../../assets/icons/shopping-cart-svgrepo-com.png"),
  star: require("../../../assets/icons/star-svgrepo-com.png"),
  sun: require("../../../assets/icons/sun-svgrepo-com.png"),
  support: require("../../../assets/icons/support-svgrepo-com.png"),
};
