import { ImageURISource } from "react-native";
import { AppIconNames } from "./types";

export const icons: { [key in AppIconNames]: ImageURISource } = {
  [AppIconNames.AcademicCap]: require("../../assets/icons/academic-cap-svgrepo-com.png"),
  [AppIconNames.Aerial]: require("../../assets/icons/aerial-svgrepo-com.png"),
  [AppIconNames.Airplane]: require("../../assets/icons/airplane-svgrepo-com.png"),
  [AppIconNames.AtSymbol]: require("../../assets/icons/at-symbol-svgrepo-com.png"),
  [AppIconNames.Bitcoin]: require("../../assets/icons/bitcoin-svgrepo-com.png"),
  [AppIconNames.BookOpen]: require("../../assets/icons/book-open-svgrepo-com.png"),
  [AppIconNames.Bookmark]: require("../../assets/icons/bookmark-svgrepo-com.png"),
  [AppIconNames.Box]: require("../../assets/icons/box-svgrepo-com.png"),
  [AppIconNames.BriefcaseAlt]: require("../../assets/icons/briefcase-alt-svgrepo-com.png"),
  [AppIconNames.Building]: require("../../assets/icons/building-svgrepo-com.png"),
  [AppIconNames.BulbOn]: require("../../assets/icons/bulb-on-svgrepo-com.png"),
  [AppIconNames.Cake]: require("../../assets/icons/cake-svgrepo-com.png"),
  [AppIconNames.Cash]: require("../../assets/icons/cash-svgrepo-com.png"),
  [AppIconNames.CodeAlt]: require("../../assets/icons/code-alt-svgrepo-com.png"),
  [AppIconNames.CreditCard]: require("../../assets/icons/credit-card-svgrepo-com.png"),
  [AppIconNames.Desktop]: require("../../assets/icons/desktop-svgrepo-com.png"),
  [AppIconNames.Diamond]: require("../../assets/icons/diamond-svgrepo-com.png"),
  [AppIconNames.Dollar]: require("../../assets/icons/dollar-svgrepo-com.png"),
  [AppIconNames.Edit]: require("../../assets/icons/edit-svgrepo-com.png"),
  [AppIconNames.Frame1]: require("../../assets/icons/Frame-1.png"),
  [AppIconNames.Frame2]: require("../../assets/icons/Frame-2.png"),
  [AppIconNames.Frame]: require("../../assets/icons/Frame.png"),
  [AppIconNames.Ghost]: require("../../assets/icons/ghost-svgrepo-com.png"),
  [AppIconNames.Gift]: require("../../assets/icons/gift-svgrepo-com.png"),
  [AppIconNames.Globe]: require("../../assets/icons/globe-svgrepo-com.png"),
  [AppIconNames.Goblet]: require("../../assets/icons/goblet-svgrepo-com.png"),
  [AppIconNames.Heart]: require("../../assets/icons/heart-svgrepo-com.png"),
  [AppIconNames.HomeAlt]: require("../../assets/icons/home-alt-svgrepo-com.png"),
  [AppIconNames.Keyboard]: require("../../assets/icons/keyboard-svgrepo-com.png"),
  [AppIconNames.Lamp]: require("../../assets/icons/lamp-svgrepo-com.png"),
  [AppIconNames.Mobile]: require("../../assets/icons/mobile-svgrepo-com.png"),
  [AppIconNames.MoreHorizontal]: require("../../assets/icons/more-horizontal-svgrepo-com.png"),
  [AppIconNames.Mug]: require("../../assets/icons/mug-svgrepo-com.png"),
  [AppIconNames.Phone]: require("../../assets/icons/phone-svgrepo-com.png"),
  [AppIconNames.Scissors]: require("../../assets/icons/scissors-svgrepo-com.png"),
  [AppIconNames.ShoppingBag]: require("../../assets/icons/shopping-bag-svgrepo-com.png"),
  [AppIconNames.ShoppingCart]: require("../../assets/icons/shopping-cart-svgrepo-com.png"),
  [AppIconNames.Star]: require("../../assets/icons/star-svgrepo-com.png"),
  [AppIconNames.Sun]: require("../../assets/icons/sun-svgrepo-com.png"),
  [AppIconNames.Support]: require("../../assets/icons/support-svgrepo-com.png"),
};
